# Generated by Django 2.2.12 on 2020-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='businesses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_contact', models.CharField(max_length=100)),
                ('business_location', models.CharField(max_length=100)),
                ('business_url', models.CharField(max_length=100)),
                ('business_description', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_price', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('event_contact', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_job', models.CharField(max_length=100)),
                ('type_of_job', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('location_of_job', models.CharField(max_length=100)),
                ('url_of_company', models.CharField(max_length=100)),
                ('description_of_job', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
