# Generated by Django 2.2.12 on 2020-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200513_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
