# Generated by Django 2.2.12 on 2020-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200513_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='business_of',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_of',
            field=models.CharField(default='aanish', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_of',
            field=models.CharField(default='aanish', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
