# Generated by Django 2.2.12 on 2020-05-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20200517_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
