# Generated by Django 2.2.12 on 2020-05-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='business_type',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
