# Generated by Django 2.2.12 on 2020-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_password_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('like', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
            ],
        ),
    ]
