# Generated by Django 2.2.12 on 2020-05-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_business_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_stats',
            name='full_name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
