# Generated by Django 2.2.12 on 2020-05-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_business_stats_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_stats',
            name='comment_text',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
