# Generated by Django 2.2.12 on 2020-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_business_stats_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100)),
                ('event_price', models.IntegerField()),
                ('reference_number', models.CharField(max_length=100)),
            ],
        ),
    ]
