# Generated by Django 2.2.12 on 2020-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, upload_to='job_images'),
        ),
    ]
