# Generated by Django 2.2.12 on 2020-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_jobs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='image',
            field=models.ImageField(blank=True, upload_to='business_images'),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_images'),
        ),
    ]
